In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("D:/Lambton AIMT/Term 3/Capstone Project/digits.csv")
print(df.shape)
df.head()

(94257, 1025)


0    1    2    3    4    5    6    7    8    9  ...  1015  1016  1017  \
0  255  255  255  255  255  255  255  253  254  254  ...   255   255   255   
1  255  255  255  255  255  255  255  255  255  255  ...   255   255   254   
2  255  255  255  255  255  255  255  255  255  255  ...   255   255   255   
3  255  255  255  255  255  255  253  255  254  255  ...   255   255   255   
4  255  255  255  255  255  255  254  254  254  254  ...   226    59   255   

   1018  1019  1020  1021  1022  1023  label  
0   255   255   255   255   255   255      4  
1    60   255   255   255   255   255      1  
2   255   255   255   255   255   255      1  
3   255   255   255   255   255   255      6  
4   254   253   255   255   255   255      4  

[5 rows x 1025 columns]

In [16]:
df = df.sample(frac=1)
df_ = df.iloc[:5000, :]
df_.head()

0    1    2    3    4    5    6    7    8    9  ...  1015  1016  \
13756  255  255  255  255  255  255  255  255  255  255  ...   255   255   
7159   255  255  255  255  255  255  253  255  255   80  ...   255   255   
73966  255  255  255  255  255  255  255  255  255  255  ...   255   255   
68490  255  255  255  255  255  255  255  252  255  255  ...   254   253   
28714  255  255  255  255  255  255  255  255  255  255  ...   255   255   

       1017  1018  1019  1020  1021  1022  1023  label  
13756   255   255   255   255   255   255   255      2  
7159    255   255   255   255   255   255   255      3  
73966   255   255   255   255   255   255   255      1  
68490   254   254   253   255   255   255   255      2  
28714   255   255   255   255   255   255   255      1  

[5 rows x 1025 columns]

In [17]:
X = df_.drop('label', axis=1)
y = df_['label']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [18]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [19]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 84   2   3   0   0   0   0   0   0   0]
 [  0 315  11   0   1   2   1   0   0   0]
 [  1  12 332   2   2   0   0   1   1   0]
 [  1   4   3 144   1   3   0   2   0   0]
 [  0  13   2   0  71   0   3   2   0   0]
 [  0   0   2   9   1  40   0   0   0   1]
 [  0   1   1   0   0   2  29   0   0   0]
 [  0   3   0   3   1   0   0  27   0   0]
 [  0   1   3   5   0   1   2   0  46   0]
 [  3   6   2   1   1   0   0   0   0  40]]


0.9024

In [48]:
df_symb = pd.read_csv("D:/Lambton AIMT/Term 3/Capstone Project/math_symbols.csv")
print(df_symb.shape)
df_symb = df_symb.sample(frac=1)

(124697, 1025)


In [49]:
df_symb_ = df_symb.iloc[:2000, :]
df_symb_ = df_symb_['label'].astype('string')
df_symb_['label'].unique()

array(['mul', ')', 'add', '(', 'sub', 'sqrt', 'pi', 'eq', ',', '!', '{',
       ']', 'lt', 'leq', '}', '[', 'neq', 'geq', 'div', 'gt'],
      dtype=object)

In [50]:
X = df_symb_.drop('label', axis=1)
y = df_symb_['label']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  4   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  66   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  46   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   2   2   0   0   0   2   0   0   0   2   0   0   0   0]
 [  0   0   3   0   3   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   2   0   0  95   0   2   0   0   0   0   0   0   1   0]
 [  1   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0]
 [  0   0   1   0   0   1   0  40   0   0   0   0   0   0   1   0]
 [  0   0   0   0   0   1   0   0   1   0   0   0   0   0   0   0]
 [  0   0   0   0   0   1   0   0   0   3   0   0   0   1   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   3   0]
 [  0   0   0   0   0   8   0   0   0   0   0  19   0   0   0   0]
 [  0   0   0   0   0   3   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   2   0   3   0   0   0   1   0   2   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0  38 

0.916

In [54]:
main_frame = pd.concat([df_, df_symb_])
main_frame['label'].unique()

array([2, 3, 1, 6, 7, 9, 8, 0, 4, 5, 'mul', ')', 'add', '(', 'sub',
       'sqrt', 'pi', 'eq', ',', '!', '{', ']', 'lt', 'leq', '}', '[',
       'neq', 'geq', 'div', 'gt'], dtype=object)

In [52]:
type(main_frame.iloc[1, -1])

int

In [55]:
X = main_frame.drop('label', axis=1)
y = main_frame['label'].astype('string')
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  4   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0]
 [  0  53   0   0   0  13   1   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  40   0   0   1   0   0   0   0   0   0   0   0   0   1   0   0
    0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   1   1   0   1   0   0   0   0   0   0   0   0   0   0   0   0
    1   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0  79   3   4   0   0   0   0   0   0   0   0   0   0   0
    1   0   0   0   0   0   0   0   0   0   0]
 [  0  13   5   2   0 312   7   1   0   0   1   0   0   0   0   0   0   0
    3   0   0   0   0   0   0   0   1   0   0]
 [  0   0   1   0   5  10 328   1   1   0   0   0   0   0   0   0   1   0
    4   0   0   0   0   0   0   0   0   0   0]
 [  0   0   6   0   0   0   1 136   1   2   0   5   0   3   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   5   0   

0.8708571428571429